services:

  users_api:
    build:
      context: ./APIS
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.15"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
    ports:
      - "52000:3000"
    volumes:
      - ./APIS/users/:/usr/usersAPI/
    depends_on:
      - db
    networks:
      - dev_network

  db:
    image: mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 2GB
        reservations:
          cpus: "0.1"
          memory: 1GB
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    ports:
      - "3307:3306"
    volumes:
      - ./pgdata/users:/var/lib/mysql  # Note: changed the path to match MySQL
networks:
  dev_network:
    driver: bridge
